---
title: "Workbook for Plotting Figures"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MTS)
library(expm)
library(MASS)
library(zoo)
```

## Global variables
```{r global variables}
P = 100 # Number of Sample Path
path = P
T_1m = 21
T_3m = 63 # T_1m / 4
T = T_3m  # Length of simulation Series
# parameters
#r_1m = 0.0223/360 #daily rate for one-month investment
#r_3m = 0.0234/360 #daily rate for three-month investment
dailyRiskFeeRate <- 0.024585/360
g    = 2 
I_0  = c(1000000, 1000000) #Initial investment level I_0 for each stock in portfolio
V_0  = c(1000000, 1000000) #Initial account value V_0 for each stock in portfolio
I_min = 1000000 * 0.2   # 20% of initial investment level
pct99 = 0.99
pct95 = 0.95
```

## Helper Functions 
##   copy from SLS.Rmd
```{r helper functions}
## GSLS for a portfolio of two stocks
## parameters
## price1, price2: n by t matrix, where n is number of paths, 
##                 and t must be 63 days, which is three month trading days
GSLS_Ptfl <- function(price1, price2, I0, V0, alpha, beta, gamma, K, r, Imin) {
  
  ## core function begin
  numPath = nrow(price1)
  T       = ncol(price1)

  ## Check for Inconsistency
  if ((numPath != nrow(price2)) | (T != ncol(price2))) {
    message("Inconsistent Price Matrix Size")
    stop
  }
  
  ## result is an 1 x numPath vector of gain at terminal T
  vResult = rep(0,numPath)
  gResult = rep(0,numPath)

  v3mResult = rep(0,numPath)
  v1mResult = rep(0,numPath)
    
  allV = matrix(rep(0,T*numPath), nrow=numPath)
  
  for (j in 1:numPath) {
    # initialization
    I <- matrix(rep(0,2*T),nrow=2)
    IL <- matrix(rep(0,2*T),nrow=2)
    IS <- matrix(rep(0,2*T),nrow=2)
    g  <- matrix(rep(0,2*T),nrow=2)
    gL <- matrix(rep(0,2*T),nrow=2)
    gS <- matrix(rep(0,2*T),nrow=2)
    rho <- matrix(rep(0,2*T),nrow=2)
    V <- rep(0,T)
    ctrlrReset <- matrix(rep(0,2*T),nrow=2)
    
    for (t in 1:T) {
      if (t == 1) {
        gL[,t] <- c(0,0)
        gS[,t] <- c(0,0)
        g[,t]  <- gL[,t] + gS[,t]
        
        IL[,t] <-  I0
        IS[,t] <- -alpha*I0
        V[t]  <- V0
        I[,t]  <- IL[,t] + IS[,t]
        ctrlrReset[1,t] <- min(IL[1,t], abs(IS[1,t])/alpha)
        ctrlrReset[2,t] <- min(IL[2,t], abs(IS[2,t])/alpha)
        allV[j,t] = V[t]
      } else {
        rho[1,t] <- (price1[j,t] - price1[j,t-1]) / price1[j,t-1]
        rho[2,t] <- (price2[j,t] - price2[j,t-1]) / price2[j,t-1]
        gL[,t]  <- gL[,t-1] + rho[,t]*IL[,t-1]
        gS[,t]  <- gS[,t-1] + rho[,t]*IS[,t-1]
        g[,t]   <- gL[,t] + gS[,t]
        V[t]   <- V[t-1] + sum(g[,t]) - sum(g[,t-1]) + r*(V[t-1]-sum(abs(I[,t-1])))
        # for plotting return path
        allV[j,t] = V[t]

        # CHANGE:  should update I[,t] first 
          IL[1,t]  <- max( (1+K*rho[1,t])*IL[1,t-1],0 )
          IS[1,t]  <- min( (1-beta*K*rho[1,t])*IS[1,t-1], 0 )
          IL[2,t]  <- max( (1+K*rho[2,t])*IL[2,t-1],0 )
          IS[2,t]  <- min( (1-beta*K*rho[2,t])*IS[2,t-1], 0 )
          ctrlrReset[1,t] <- min(IL[1,t], abs(IS[1,t])/alpha)
          ctrlrReset[2,t] <- min(IL[2,t], abs(IS[2,t])/alpha) 

        if (ctrlrReset[1,t] < Imin)  {  
          # controller reset
          IL[1,t]  <- IL[1,1]
          IS[1,t]  <- IS[1,1]
        }
        if (ctrlrReset[2,t] < Imin) {
          # controller reset
          IL[2,t]  <- IL[2,1]
          IS[2,t]  <- IS[2,1]
        }
          I[,t] <- IL[,t] + IS[,t]
        # In a margin call, IL and IS need to be adjusted accordingly
        if (sum(abs(I[,t])) > gamma*V[t-1]){
          IL[,t]  <- IL[,t] * gamma*V[t-1] /(sum(abs(I[,t])))
          IS[,t]  <- IS[,t] * gamma*V[t-1] /(sum(abs(I[,t])))
          I[,t] <- IL[,t] + IS[,t]
        }
          
        if (is.na(ctrlrReset[1,t])) {
          message("t=", t, " rho[1,t]=", rho[1,t], " IL[1,t]=", IL[1,t], " IL[1,t-1]=", IL[1,t-1], " IS[1,t]=", IS[1,t], " alpha=", alpha, " beta=", beta, " gamma=", gamma)
        }
        if (is.na(ctrlrReset[2,t])) {
          message("t=", t, " rho[2,t]=", rho[2,t], " IL[2,t]=", IL[2,t], " IL[2,t-1]=", IL[2,t-1], " IS[1,t]=", IS[2,t], " alpha=", alpha, " beta=", beta, " gamma=", gamma)
        }
  
      }
    }
    vResult[j] = V[T]
    gResult[j] = sum(g[,T])
    
    v1mResult[j] = V[T_1m]
    v3mResult[j] = V[T_3m]
  }
  
  result = list(      acctVal = vResult, 
                      Invest = I,
                      V= V,
                      return1m = (v1mResult-V0)/V0, # for plotting graph
                      return3m = (v3mResult-V0)/V0, # for plotting graph
                      return  = (vResult-V0)/V0, 
                      gain = gResult,
                      allV  = allV)
  
  return(result)
}

## GSLS for single stock
## parameters
## price: n by t matrix, where n is number of paths, and t must be 63 days, which is three month trading days
GSLS <- function(price, I0, V0, alpha, beta, gamma, K, r, Imin) {
  
  ## core function begin
  numPath = nrow(price)
  T       = ncol(price)
  
  ## result is an 1 x numPath vector of gain at terminal T
  g3mResult = rep(0,numPath)
  v3mResult = rep(0,numPath)
  g1mResult = rep(0,numPath)
  v1mResult = rep(0,numPath)
  
  allV = matrix(rep(0,T*numPath), nrow=numPath)
  
  for (j in 1:numPath) {
    # initialization
    I   <- rep(0,T)
    IL  <- rep(0,T)
    IS  <- rep(0,T)
    g   <- rep(0,T)
    gL  <- rep(0,T)
    gS  <- rep(0,T)
    rho <- rep(0,T)
    V   <- rep(0,T)
    ctrlrReset <- rep(0,T)
    
    for (t in 1:T) {
      if (t == 1) {
        gL[t] <- 0
        gS[t] <- 0
        g[t]  <- gL[t] + gS[t]
        IL[t] <-  I0
        IS[t] <- -alpha*I0
        V[t]  <- V0
        I[t]  <- IL[t]+ IS[t]
        ctrlrReset[t] <- min(IL[t], abs(IS[t]))
        allV[j,t] = V[t]
      } else {
        rho[t] <- (price[j,t] - price[j,t-1]) / price[j,t-1]
        gL[t]  <- gL[t-1] + rho[t]*IL[t-1]
        gS[t]  <- gS[t-1] + rho[t]*IS[t-1]
        g[t]   <- gL[t] + gS[t]
        V[t]   <- V[t-1] + g[t] - g[t-1] + r*(V[t-1]-abs(I[t-1]))
        # for plotting return path
        allV[j,t] = V[t]

        if (ctrlrReset[t-1] >= Imin) {
          #normal case
          IL[t]  <- max( (1+K*rho[t])*IL[t-1], 0 )
          IS[t]  <- min( (1-beta*K*rho[t])*IS[t-1], 0 )
        } else {  
          # controller reset
          IL[t]  <- IL[1]
          IS[t]  <- IS[1]
          I[t] <- 0
        }
        # In a margin call, IL and IS need to be adjusted accordingly
        if (abs(IL[t]+IS[t]) > gamma*V[t-1]){
          IL[t]  <- IL[t] * gamma*V[t-1] /(abs(IL[t]+IS[t]))
          IS[t]  <- IS[t] * gamma*V[t-1] /(abs(IL[t]+IS[t]))
          I[t] <- IL[t] + IS[t]
        }
        ctrlrReset[t] <- min( IL[t], abs(IS[t])/alpha )
      }
    }
    
    g3mResult[j] = g[T_3m]
    v3mResult[j] = V[T_3m]
    g1mResult[j] = g[T_1m]
    v1mResult[j] = V[T_1m]
  }

  result = list(gain3m    = g3mResult, 
                acctVal3m = v3mResult, 
                return3m  = (v3mResult-V0)/V0, 
                gain1m    = g1mResult, 
                acctVal1m = v1mResult,
                return1m  = (v1mResult-V0)/V0,
                allV  = allV)
  
  return(result)
}

getVaR <- function(samples, VaRValue) {
  samples = sort(samples)
  len = length(samples)
  alpha = round( len * (1-VaRValue) )
  VaR = -1 * samples[alpha]
  return(VaR)
}

getES <- function(inSamples, VaRValue) {
  sortedSamples = sort(inSamples)
  len = length(sortedSamples)
  alpha = round( len * (1-VaRValue) )
  ES = -1 * sum(sortedSamples[1:alpha])/alpha
  return(ES)
}
```

Pre-requisite: bekkData.rda and gbmData.rda were obtained from SLS.Rmd

```{r data for analysis}
###################
# change a, b and k for plotting graphs for specific alpha/beta/K combination
###################
a = 1
b = 0.5
k = 1
###################

# use offline simulation data
rm(S1_gen, S2_gen, Output_BEKK_AAPL, Output_BEKK_AMZN)
load(file = "bekkData.rda")
load(file = "gbmData.rda")

simulationResults <- data.frame(alpha=double(),
                        beta=double(),
                        K=double(),
                        VaR99_1m_GBM_PTFL=double(), 
                        VaR99_1m_GARCH_PTFL=double(), 
                        ES99_1m_GBM_PTFL=double(), 
                        ES99_1m_GARCH_PTFL=double(),
                        mean_1m_GBM_PTFL=double(),
                        mean_1m_GARCH_PTFL=double(),
                        median_1m_GBM_PTFL=double(),
                        median_1m_GARCH_PTFL=double(),
                        VaR99_3m_GBM_PTFL=double(), 
                        VaR99_3m_GARCH_PTFL=double(), 
                        ES99_3m_GBM_PTFL=double(), 
                        ES99_3m_GARCH_PTFL=double(),
                        mean_3m_GBM_PTFL=double(),
                        mean_3m_GARCH_PTFL=double(),
                        median_3m_GBM_PTFL=double(),
                        median_3m_GARCH_PTFL=double()
                        )
sum_V_0 = sum(V_0)


      # rs stands for result set
      rsBS_ptfl <- GSLS_Ptfl(price1 = S1_gen, price2 = S2_gen,I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
      
      rsBEKK_ptfl <- GSLS_Ptfl(price1 = Output_BEKK_AAPL, price2 = Output_BEKK_AMZN,I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)

      # initialize portfolio calculation
      gbmPftlRet3m   = rsBS_ptfl$return3m
      gbmPftlRet1m   = rsBS_ptfl$return1m
      garchPftlRet3m = rsBEKK_ptfl$return3m 
      garchPftlRet1m = rsBEKK_ptfl$return1m

      # plot histogram and denity curve
      
      #### on gain
      hist( rsBS_ptfl$gain,   main=paste("Histogram of Portfolio Gain under BS Model \n with alpha=", a, " beta=", b, " K=", k, "T=3 Month"), xlim =c(min(rsBS_ptfl$gain)-0.01, max(rsBS_ptfl$gain)+0.01),breaks = 20, xlab="Gain")
      dens=density(rsBS_ptfl$gain)
      lines(dens$x,length(rsBS_ptfl$gain) * (max(rsBS_ptfl$gain) - min(rsBS_ptfl$gain)) *dens$y / 20) 
      abline(v=mean(rsBS_ptfl$gain),col=3) # green line for mean
      abline(v=-getVaR(rsBS_ptfl$gain, pct99),col=2) # red line for 99% VaR
      
      hist( rsBEKK_ptfl$gain,   main=paste("Histogram of Portfolio Gain under GARCH Model \n with alpha=", a, " beta=", b, " K=", k, "T=3 Month"), xlim =c(min(rsBEKK_ptfl$gain)-0.01, max(rsBEKK_ptfl$gain)+0.01),breaks = 20, xlab="Gain")
      dens=density(rsBEKK_ptfl$gain)
      lines(dens$x,length(rsBS_ptfl$gain) * (max(rsBEKK_ptfl$gain) - min(rsBEKK_ptfl$gain)) *dens$y / 20) 
      abline(v=mean(rsBEKK_ptfl$gain),col=3) # green line for mean
      abline(v=-getVaR(rsBEKK_ptfl$gain, pct99),col=2) # red line for 99% VaR      
      ####
      
      hist( gbmPftlRet1m,   main=paste("Histogram of Portfolio Return under BS Model \n with alpha=", a, " beta=", b, " K=", k, "T=1 Month"), xlim =c(min(gbmPftlRet1m)-0.01, max(gbmPftlRet1m)+0.01),breaks = 20, xlab="Return")
      dens=density(gbmPftlRet1m)
      lines(dens$x,length(gbmPftlRet1m) * (max(gbmPftlRet1m) - min(gbmPftlRet1m)) *dens$y / 20) 
      abline(v=mean(gbmPftlRet1m),col=3) # green line for mean
      abline(v=-getVaR(gbmPftlRet1m, pct99),col=2) # red line for 99% VaR
      
      hist( garchPftlRet1m, main=paste("Histogram of Portfolio Return under GARCH Model \n with alpha =", a, " beta=", b, " K=", k, "T=1 Month"), xlim =c(min(garchPftlRet1m)-0.01, max(garchPftlRet1m)+0.01),breaks = 20, xlab="Return")
      dens=density(garchPftlRet1m)
      lines(dens$x,length(garchPftlRet1m) * (max(garchPftlRet1m) - min(garchPftlRet1m)) *dens$y / 20) 
      abline(v=mean(garchPftlRet1m),col=3) # green line for mean
      abline(v=-getVaR(garchPftlRet1m, pct99),col=2) # red line for 99% VaR
      
      hist( gbmPftlRet3m,   main=paste("Histogram of Portfolio Return under BS Model \n with alpha=", a, " beta=", b, " K=", k, "T=3 Months"), xlim =c(min(gbmPftlRet3m)-0.01, max(gbmPftlRet3m)+0.01),breaks = 20, xlab="Return")
      dens=density(gbmPftlRet3m)
      lines(dens$x,length(gbmPftlRet3m) * (max(gbmPftlRet3m) - min(gbmPftlRet3m)) *dens$y / 20) 
      abline(v=mean(gbmPftlRet3m),col=3) # green line for mean
      abline(v=-getVaR(gbmPftlRet3m, pct99),col=2) # red line for 99% VaR
      
      hist( garchPftlRet3m, main=paste("Histogram of Portfolio Return under GARCH Model with \n alpha =", a, " beta =", b, " K=", k, "T = 3 Months"), xlim =c(min(garchPftlRet3m)-0.01, max(garchPftlRet3m)+0.01),breaks = 20, xlab="Return")
      dens=density(garchPftlRet3m)
      lines(dens$x,length(garchPftlRet3m) * (max(garchPftlRet3m) - min(garchPftlRet3m)) *dens$y / 20)
      abline(v=mean(garchPftlRet3m),col=3) # green line for mean
      abline(v=-getVaR(garchPftlRet3m, pct99),col=2) # red line for 99% VaR
            
      # plot contour
      sample = apply( (rsBS_ptfl$allV - sum_V_0) / sum_V_0, 2, quantile, probs=c(0.01, 0.5, 0.99))
      plot.zoo(t( (rsBS_ptfl$allV - sum_V_0) / sum_V_0 ), main = paste("Sample Return Paths and Empirical Confidence Envelope\n(BS Model) ", "alpha=", a, " beta=", b, " K=", k), xlab="t", ylab="Portfolio Return", plot.type = "single")
      lines(sample[1,],col="Red",lwd=2)
      lines(sample[2,],col="Red",lwd=2)
      lines(sample[3,],col="Red",lwd=2)
      #plot(c(1:253, 1:253, 1:253), c(sample[1,],sample[2,],sample[3,]), type="l", main=paste("Contour of Portfolio Simulation based on GBM Model", "alpha =", a, " beta =", b, " K=", k), xlab="time", ylab="pct return")
      abline(h=0,col=3) # green line for 0

      
      sample = apply( (rsBEKK_ptfl$allV - sum_V_0) / sum_V_0, 2, quantile, probs=c(0.01, 0.5, 0.99))
      plot.zoo(t((rsBEKK_ptfl$allV - sum_V_0) / sum_V_0), main = paste("Sample Return Paths and Empirical Confidence Envelope\n(BEKK Model) ", "alpha=", a, " beta=", b, " K=", k), xlab="t", ylab="Portfolio Return", plot.type = "single")
      lines(sample[1,],col="Red",lwd=2)
      lines(sample[2,],col="Red",lwd=2)
      lines(sample[3,],col="Red",lwd=2)
      #plot(c(1:253, 1:253, 1:253), c(sample[1,],sample[2,],sample[3,]), type="l", main=paste("ontour of Portfolio Simulation based on BEKK Model", "alpha =", a, " beta =", b, " K=", k), xlab="time", ylab="pct return")
      abline(h=0,col=3) # green line for 0

      
      #save stimulation result
      stimulationRec <- data.frame(alpha=a,
                        beta=b,
                        K=k,
                        ### 3 mths
                        VaR99_3m_GBM_PTFL  =getVaR(gbmPftlRet3m, pct99), 
                        VaR99_3m_GARCH_PTFL=getVaR(garchPftlRet3m, pct99), 
                        ES99_3m_GBM_PTFL   =getES(gbmPftlRet3m, pct99), 
                        ES99_3m_GARCH_PTFL =getES(garchPftlRet3m, pct99),
                        mean_3m_GBM_PTFL=mean(gbmPftlRet3m),
                        mean_3m_GARCH_PTFL=mean(garchPftlRet3m),
                        median_3m_GBM_PTFL=median(gbmPftlRet3m),
                        median_3m_GARCH_PTFL=median(garchPftlRet3m),
                        
                        ### 1 month
                        VaR99_1m_GBM_PTFL  =getVaR(gbmPftlRet1m, pct99), 
                        VaR99_1m_GARCH_PTFL=getVaR(garchPftlRet1m, pct99), 
                        ES99_1m_GBM_PTFL   =getES(gbmPftlRet1m, pct99), 
                        ES99_1m_GARCH_PTFL =getES(garchPftlRet1m, pct99),
                        mean_1m_GBM_PTFL=mean(gbmPftlRet1m),
                        mean_1m_GARCH_PTFL=mean(garchPftlRet1m),
                        median_1m_GBM_PTFL=median(gbmPftlRet1m),
                        median_1m_GARCH_PTFL=median(garchPftlRet1m)
                        )
      simulationResults <- rbind(simulationResults, stimulationRec)

save(simulationResults, file = "simulationResults.rda")
write.csv(simulationResults,'simulationResults.csv')
```

```{r}
# a=1
# b=0.5
# k=1
# rsBS_ptfl <- GSLS_Ptfl(price1 = S1_gen, price2 = S2_gen,I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)

rm(S1_gen, S2_gen, Output_BEKK_AAPL, Output_BEKK_AMZN)
load(file = "bekkData10k.rda")
load(file = "gbmData10k.rda")


library(ggplot2)

# rsBS_ptfl

length(rsBS_ptfl$return1m)
t = seq(1,10000)
length(t)

plotData = data.frame(return1m <- rsBS_ptfl$return1m, x_t <- t)

ggplot(data=plotData, aes(plotData$return1m)) + 
  geom_histogram(
    center=TRUE,
    breaks=seq(-0.1, 0.15, by=0.005),
                 col="red", 
                 fill="green", 
                 alpha = .2) + 
  labs(title="..................") +  geom_density(col=5) 

+geom_freqpoly()

ggplot(data=plotData, aes(plotData$return1m)) + geom_histogram() 

# g <- ggplot(plotData, aes(x=x_t, y=ret))

g1 <- ggplot(plotData, aes(x=x_t, y=ret)) + geom_histogram() + geom_smooth(method="lm") 

g1 + labs(title="Area Vs Population", subtitle="From midwest dataset", y="Population", x="Area", caption="Midwest Demographics")

g1 + ggtitle("Area Vs Population", subtitle="From midwest dataset") + xlab("Area") + ylab("Population")

```

