---
title: "RMSC5003 Project"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
Description
This 

Release notes
* Please run this in RStudio

## Set Up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("quantmod")
# install.packages("fGarch")
# install.packages("MTS")
# install.packages("expm")
# install.packages("MASS")
# install.packages("zoo")
```

## Get stock price
```{r get stock price}
library(quantmod)

price_AAPL = getSymbols("AAPL", from ="2015-11-15", to = "2018-11-14", auto.assign = FALSE)
price_AMZN = getSymbols("AMZN", from ="2015-11-15", to = "2018-11-14", auto.assign = FALSE)

save(price_AAPL, price_AMZN, file = "StockPriceData.rda")
```

## Global variables
```{r global variables}
P = 100 # Number of Sample Path
path = P
T_1m = 21
T_3m = 63 # T_1m / 4
T = T_3m  # Length of simulation Series
# parameters
#r_1m = 0.0223/360 #daily rate for one-month investment
#r_3m = 0.0234/360 #daily rate for three-month investment
dailyRiskFeeRate <- 0.024585/360
g    = 2 
I_0  = c(1000000, 1000000) #Initial investment level I_0 for each stock in portfolio
V_0  = c(1000000, 1000000) #Initial account value V_0 for each stock in portfolio
I_min = 1000000 * 0.2   # 20% of initial investment level
pct99 = 0.99
pct95 = 0.95
```

## Helper Functions 
```{r helper functions}
## GSLS for a portfolio of two stocks
## parameters
## price1, price2: n by t matrix, where n is number of paths, 
##                 and t must be 63 days, which is three month trading days
GSLS_Ptfl <- function(price1, price2, I0, V0, alpha, beta, gamma, K, r, Imin) {
  
  ## core function begin
  numPath = nrow(price1)
  T       = ncol(price1)

  ## Check for Inconsistency
  if ((numPath != nrow(price2)) | (T != ncol(price2))) {
    message("Inconsistent Price Matrix Size")
    stop
  }
  
  ## result is an 1 x numPath vector of gain at terminal T
  vResult = rep(0,numPath)
  gResult = rep(0,numPath)

  v3mResult = rep(0,numPath)
  v1mResult = rep(0,numPath)
    
  allV = matrix(rep(0,T*numPath), nrow=numPath)
  
  for (j in 1:numPath) {
    # initialization
    I <- matrix(rep(0,2*T),nrow=2)
    IL <- matrix(rep(0,2*T),nrow=2)
    IS <- matrix(rep(0,2*T),nrow=2)
    g  <- matrix(rep(0,2*T),nrow=2)
    gL <- matrix(rep(0,2*T),nrow=2)
    gS <- matrix(rep(0,2*T),nrow=2)
    rho <- matrix(rep(0,2*T),nrow=2)
    V <- rep(0,T)
    ctrlrReset <- matrix(rep(0,2*T),nrow=2)
    
    for (t in 1:T) {
      if (t == 1) {
        gL[,t] <- c(0,0)
        gS[,t] <- c(0,0)
        g[,t]  <- gL[,t] + gS[,t]
        
        IL[,t] <-  I0
        IS[,t] <- -alpha*I0
        V[t]  <- V0
        I[,t]  <- IL[,t] + IS[,t]
        ctrlrReset[1,t] <- min(IL[1,t], abs(IS[1,t])/alpha)
        ctrlrReset[2,t] <- min(IL[2,t], abs(IS[2,t])/alpha)
        allV[j,t] = V[t]
      } else {
        rho[1,t] <- (price1[j,t] - price1[j,t-1]) / price1[j,t-1]
        rho[2,t] <- (price2[j,t] - price2[j,t-1]) / price2[j,t-1]
        gL[,t]  <- gL[,t-1] + rho[,t]*IL[,t-1]
        gS[,t]  <- gS[,t-1] + rho[,t]*IS[,t-1]
        g[,t]   <- gL[,t] + gS[,t]
        V[t]   <- V[t-1] + sum(g[,t]) - sum(g[,t-1]) + r*(V[t-1]-sum(abs(I[,t-1])))
        # for plotting return path
        allV[j,t] = V[t]

        # CHANGE:  should update I[,t] first 
          IL[1,t]  <- max( (1+K*rho[1,t])*IL[1,t-1],0 )
          IS[1,t]  <- min( (1-beta*K*rho[1,t])*IS[1,t-1], 0 )
          IL[2,t]  <- max( (1+K*rho[2,t])*IL[2,t-1],0 )
          IS[2,t]  <- min( (1-beta*K*rho[2,t])*IS[2,t-1], 0 )
          ctrlrReset[1,t] <- min(IL[1,t], abs(IS[1,t])/alpha)
          ctrlrReset[2,t] <- min(IL[2,t], abs(IS[2,t])/alpha) 

        if (ctrlrReset[1,t] < Imin)  {  
          # controller reset
          IL[1,t]  <- IL[1,1]
          IS[1,t]  <- IS[1,1]
        }
        if (ctrlrReset[2,t] < Imin) {
          # controller reset
          IL[2,t]  <- IL[2,1]
          IS[2,t]  <- IS[2,1]
        }
          I[,t] <- IL[,t] + IS[,t]
        # In a margin call, IL and IS need to be adjusted accordingly
        if (sum(abs(I[,t])) > gamma*V[t-1]){
          IL[,t]  <- IL[,t] * gamma*V[t-1] /(sum(abs(I[,t])))
          IS[,t]  <- IS[,t] * gamma*V[t-1] /(sum(abs(I[,t])))
          I[,t] <- IL[,t] + IS[,t]
        }
          
        if (is.na(ctrlrReset[1,t])) {
          message("t=", t, " rho[1,t]=", rho[1,t], " IL[1,t]=", IL[1,t], " IL[1,t-1]=", IL[1,t-1], " IS[1,t]=", IS[1,t], " alpha=", alpha, " beta=", beta, " gamma=", gamma)
        }
        if (is.na(ctrlrReset[2,t])) {
          message("t=", t, " rho[2,t]=", rho[2,t], " IL[2,t]=", IL[2,t], " IL[2,t-1]=", IL[2,t-1], " IS[1,t]=", IS[2,t], " alpha=", alpha, " beta=", beta, " gamma=", gamma)
        }
  
      }
    }
    vResult[j] = V[T]
    gResult[j] = sum(g[,T])
    
    v1mResult[j] = V[T_1m + 1]
    v3mResult[j] = V[T_3m + 1]
  }
  
  result = list(      acctVal = vResult, 
                      Invest = I,
                      V= V,
                      return1m = (v1mResult-V0)/V0, # for plotting graph
                      return3m = (v3mResult-V0)/V0, # for plotting graph
                      return  = (vResult-V0)/V0, 
                      gain = gResult,
                      allV  = allV)
  
  return(result)
}

## GSLS for single stock
## parameters
## price: n by t matrix, where n is number of paths, and t must be 63 days, which is three month trading days
GSLS <- function(price, I0, V0, alpha, beta, gamma, K, r, Imin) {
  
  ## core function begin
  numPath = nrow(price)
  T       = ncol(price)
  
  ## result is an 1 x numPath vector of gain at terminal T
  g3mResult = rep(0,numPath)
  v3mResult = rep(0,numPath)
  g1mResult = rep(0,numPath)
  v1mResult = rep(0,numPath)
  
  allV = matrix(rep(0,T*numPath), nrow=numPath)
  
  for (j in 1:numPath) {
    # initialization
    I   <- rep(0,T)
    IL  <- rep(0,T)
    IS  <- rep(0,T)
    g   <- rep(0,T)
    gL  <- rep(0,T)
    gS  <- rep(0,T)
    rho <- rep(0,T)
    V   <- rep(0,T)
    ctrlrReset <- rep(0,T)
    
    for (t in 1:T) {
      if (t == 1) {
        gL[t] <- 0
        gS[t] <- 0
        g[t]  <- gL[t] + gS[t]
        IL[t] <-  I0
        IS[t] <- -alpha*I0
        V[t]  <- V0
        I[t]  <- IL[t]+ IS[t]
        ctrlrReset[t] <- min(IL[t], abs(IS[t]))
        allV[j,t] = V[t]
      } else {
        rho[t] <- (price[j,t] - price[j,t-1]) / price[j,t-1]
        gL[t]  <- gL[t-1] + rho[t]*IL[t-1]
        gS[t]  <- gS[t-1] + rho[t]*IS[t-1]
        g[t]   <- gL[t] + gS[t]
        V[t]   <- V[t-1] + g[t] - g[t-1] + r*(V[t-1]-abs(I[t-1]))
        # for plotting return path
        allV[j,t] = V[t]

        if (ctrlrReset[t-1] >= Imin) {
          #normal case
          IL[t]  <- max( (1+K*rho[t])*IL[t-1], 0 )
          IS[t]  <- min( (1-beta*K*rho[t])*IS[t-1], 0 )
        } else {  
          # controller reset
          IL[t]  <- IL[1]
          IS[t]  <- IS[1]
          I[t] <- 0
        }
        # In a margin call, IL and IS need to be adjusted accordingly
        if (abs(IL[t]+IS[t]) > gamma*V[t-1]){
          IL[t]  <- IL[t] * gamma*V[t-1] /(abs(IL[t]+IS[t]))
          IS[t]  <- IS[t] * gamma*V[t-1] /(abs(IL[t]+IS[t]))
          I[t] <- IL[t] + IS[t]
        }
        ctrlrReset[t] <- min( IL[t], abs(IS[t])/alpha )
      }
    }
    
    g3mResult[j] = g[T_3m + 1]
    v3mResult[j] = V[T_3m + 1]
    g1mResult[j] = g[T_1m + 1]
    v1mResult[j] = V[T_1m + 1]
  }

  result = list(gain3m    = g3mResult, 
                acctVal3m = v3mResult, 
                return3m  = (v3mResult-V0)/V0, 
                gain1m    = g1mResult, 
                acctVal1m = v1mResult,
                return1m  = (v1mResult-V0)/V0,
                allV  = allV)
  
  return(result)
}

getVaR <- function(samples, VaRValue) {
  samples = sort(samples)
  len = length(samples)
  alpha = round( len * (1-VaRValue) )
  VaR = -1 * samples[alpha]
  return(VaR)
}

getES <- function(inSamples, VaRValue) {
  sortedSamples = sort(inSamples)
  len = length(sortedSamples)
  alpha = round( len * (1-VaRValue) )
  ES = -1 * sum(sortedSamples[1:alpha])/alpha
  return(ES)
}
```

## GBM stock price stimulation
```{r gbm}
library(quantmod)
#download stock1 price
S1 = getSymbols("AAPL", from ="2015-11-15", to = "2018-11-15", auto.assign = FALSE)
colnames(S1) = c("Open","High","Low","Close","Volume","Adjusted")
S1_return = (S1$Close/lag(S1$Close,1)-1)[-1] 
mu1 = mean(S1_return, na.rm=TRUE)
sigma1 = sd(S1_return, na.rm=TRUE)
#download stock2 price
S2 = getSymbols("AMZN", from ="2015-11-15", to = "2018-11-15", auto.assign = FALSE)
colnames(S2) = c("Open","High","Low","Close","Volume","Adjusted")
S2_return = (S2$Close/lag(S2$Close,1)-1)[-1]
mu2 = mean(S2_return, na.rm=TRUE)
sigma2 = sd(S2_return, na.rm=TRUE)
rho = cor(S1_return,S2_return)
# path = 100
# T = 10
dt = 1
time = (0:T)
nu1 = mu1-0.5*sigma1^2
nu2 = mu2-0.5*sigma2^2
logS1 = matrix( as.numeric(log(S1[nrow(S1),"Close"])), nrow=path, ncol=T+1 )	# n paths log price, col 1=last closing$
logS2 = matrix( as.numeric(log(S2[nrow(S2),"Close"])), nrow=path, ncol=T+1 )	
for (p in 1:path) {
  for (t in 1:T) {
    W1 = rnorm(1,0,1)
    W2 = rnorm(1,0,1)
    logS1[p, t+1] = logS1[p,t] + nu1 + sigma1*W1
    logS2[p, t+1] = logS2[p,t] + nu2 + sigma2*(rho*W1+sqrt(1-rho^2)*W2)
  }
}
S1_gen = exp(logS1)
S2_gen = exp(logS2)
#mean(log(S1_gen[,253]) - log(S1_gen[,1]))/252 # to check the mean
matplot(time,t(S1_gen),type="l")
matplot(time,t(S2_gen),type="l")
save(S1_gen, S2_gen, file='gbmData.rda')
```

```{r Garch}
library(quantmod)
library(fGarch)
############# Parameters for Adjustment ##############
# P = 100 # Number of Sample Path
# T = 10  # Length of simulation Series
############# Download stock data and calculate log-returns ##############
AAPL <- as.numeric(getSymbols("AAPL", from ="2015-11-15", to = "2018-11-15", auto.assign = FALSE)$AAPL.Close)
AMZN <- as.numeric(getSymbols("AMZN", from ="2015-11-15", to = "2018-11-15", auto.assign = FALSE)$AMZN.Close)
# Calculation Log-returns
Data <- cbind(AAPL, AMZN)
R <- apply(log(Data),2,diff)
AAPL_Return <- R[,1]
AMZN_Return <- R[,2]
# Plot returns
par(mfrow=c(2,1))
plot(AAPL_Return,type="l", xlab="Time", ylab = "AAPL", main="Historical Log-returns for AAPL") # Plot log-return series to visualize heteroskedsticity
plot(AMZN_Return,type="l", xlab="Time", ylab = "AMZN", main="Historical Log-returns for AMZN")
# Plot acf & pacf for return and squared return
acf(AAPL_Return)
acf(AMZN_Return)
pacf(AAPL_Return)
pacf(AMZN_Return)
acf(AAPL_Return^2)
acf(AMZN_Return^2)
pacf(AAPL_Return^2)
pacf(AMZN_Return^2)
# Intiate list for storing candidate models
NormModel_1 <- vector("list", 6)
NormModel_2 <- vector("list", 8)
############# Fit GARCH Model with normal innovations ###################
invisible(capture.output(NormModel_1[[1]] <- garchFit(formula ~ garch(1,0),data = AAPL_Return))) 
invisible(capture.output(NormModel_1[[2]] <- garchFit(formula ~ garch(1,1),data = AAPL_Return)))
invisible(capture.output(NormModel_1[[3]] <- garchFit(formula ~ garch(1,2),data = AAPL_Return))) 
invisible(capture.output(NormModel_1[[4]] <- garchFit(formula ~ garch(2,0),data = AAPL_Return))) 
invisible(capture.output(NormModel_1[[5]] <- garchFit(formula ~ garch(2,1),data = AAPL_Return))) 
invisible(capture.output(NormModel_1[[6]] <- garchFit(formula ~ garch(2,2),data = AAPL_Return))) 
invisible(capture.output(NormModel_2[[1]] <- garchFit(formula ~ garch(1,0),data = AMZN_Return))) 
invisible(capture.output(NormModel_2[[2]] <- garchFit(formula ~ garch(1,1),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[3]] <- garchFit(formula ~ garch(1,2),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[4]] <- garchFit(formula ~ garch(2,0),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[5]] <- garchFit(formula ~ garch(2,1),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[6]] <- garchFit(formula ~ garch(2,2),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[7]] <- garchFit(formula ~ garch(2,3),data = AMZN_Return)))
invisible(capture.output(NormModel_2[[8]] <- garchFit(formula ~ garch(3,2),data = AMZN_Return)))
# Extracing BICs for candidate models
BIC1 <- as.numeric(sapply(1:6, function(i){NormModel_1[[i]]@fit$ics[2]}))
BIC2 <- as.numeric(sapply(1:8, function(i){NormModel_2[[i]]@fit$ics[2]}))
#tModel_1 <- garchFit(formula ~ garch(1,1),data = R[,1],cond.dist = "std",include.shape = F, shape  = 4)
#tModel_2 <- garchFit(formula ~ garch(1,1),data = R[,2],cond.dist = "std",include.shape = F, shape = 4)
# Choose optimal model
NormModel_AAPL <- NormModel_1[[which.min(BIC1)]] # Choose the model with smallest BIC
NormModel_AMZN <- NormModel_2[[2]] # GARCH(1,1) is more stable and parsimonious
mu_AAPL <- NormModel_AAPL@fit$coef[1] # storing mu as in R_t = mu + epsilon_t 
Gcoef_AAPL <- NormModel_AAPL@fit$coef[-1] # storing omega, alpha, beta as in GARCH(1,1) model
mu_AMZN <- NormModel_AMZN@fit$coef[1] # storing mu as in R_t = mu + epsilon_t 
Gcoef_AMZN <- NormModel_AMZN@fit$coef[-1] # storing omega, alpha, beta as in GARCH(1,1) model
########  Simulation Based on These Model #######
###  AAPL
Sim_AAPL <- function(rept){
  #set.seed(rept)
    Sim_AAPL_return_base <- as.numeric(rep(mu_AAPL, T+1)) # estimated mu in the model
    Sim_AAPL_residual <- rep(residuals(NormModel_AAPL)[length(AAPL_Return)], T+1) # last residual as appears in GARCH model for updating
    Sim_AAPL_sigma2 <- rep(volatility(NormModel_AAPL,type = "h")[length(AAPL_Return)], T+1) # last conditional variance as appears in GARCH model for updating
    # Updating sigma_t^2 and epsilon_t recursively according to GARCH model
    for (i in 2:(T+1)){
      temp <- c(1,Sim_AAPL_residual[i-1]^2,Sim_AAPL_sigma2[i-1])
      Sim_AAPL_sigma2[i] <- t(temp) %*% Gcoef_AAPL
      Sim_AAPL_residual[i] <- sqrt(Sim_AAPL_sigma2[i]) * rnorm(1)
    }
    Sim_AAPL_return <- Sim_AAPL_return_base + Sim_AAPL_residual # as in R_t = mu (return_base) + epsilon_t(residual)
    Sim_AAPL_return[1] <- 0 ## This is artifically designed to make Sim_AAPL = the current price of AAPL
    Sim_AAPL <- as.numeric(exp(cumsum(Sim_AAPL_return)) * AAPL[length(AAPL)]) # S_t = S_0 * exp(R1 + ... + Rt)
}
#### AMZN
# Just repeat what for AAPL
Sim_AMZN <- function(rept){
  #set.seed(rept)
  Sim_AMZN_return <- as.numeric(rep(mu_AMZN, T+1))
  Sim_AMZN_residual <- rep(residuals(NormModel_AMZN)[length(AMZN_Return)], T+1)
  Sim_AMZN_residual[1] <- residuals(NormModel_AMZN)[length(AMZN_Return)-1]
  Sim_AMZN_sigma2 <- rep(volatility(NormModel_AMZN,type = "h")[length(AMZN_Return)], T+1)
  Sim_AMZN_sigma2[1] <- volatility(NormModel_AMZN,type = "h")[length(AMZN_Return)-1]
  for (i in 2:(T+1)){
    temp <- c(1,Sim_AMZN_residual[i-1]^2,Sim_AMZN_sigma2[i-1])
    Sim_AMZN_sigma2[i] <- t(temp) %*% Gcoef_AMZN
    Sim_AMZN_residual[i] <- sqrt(Sim_AMZN_sigma2[i]) * rnorm(1)
  }
  Sim_AMZN_return <- (Sim_AMZN_return + Sim_AMZN_residual)
  Sim_AMZN_return[1] <- 0
  Sim_AMZN <- as.numeric(exp(cumsum(Sim_AMZN_return)) * AMZN[length(AMZN)])
  Sim_AMZN
}
par(mfrow=c(1,1))
Output_AAPL <- t(sapply(1:P, Sim_AAPL))
Output_AMZN <- t(sapply(1:P, Sim_AMZN))
#mean(log(Output_AAPL[,253]) - log(Output_AAPL[,1]))/252 # to check the mean
save(Output_AAPL, Output_AAPL, file='garchData.rda')
```

```{r BEKK}
#install.packages("MTS")
#install.packages("expm")
#install.packages("MASS")
library(MTS)
library(expm)
library(MASS)
library(zoo)
# Fit BEKK model (bivariate GARCH Model) use log return
M2 <- BEKK11(R) # R is the 757 * 2 log-returns from independent GARCH
# Extract coefficients/parameters in BEKK model and store them in vectors/matrices
mu <- M2$estimates[1:2]
C <- matrix(c(M2$estimates[3:4],0,M2$estimates[5]), byrow=F, nrow=2)
A <- matrix(c(M2$estimates[6:9]), byrow=F, nrow=2)
B <- matrix(c(M2$estimates[10:13]), byrow=F, nrow=2)
# find the last day Residual vector and SIGMA matrix for simulation
Last.Residual <- R[length(R[,1]),] - mu
Last.SIGMA <- matrix(M2$Sigma.t[length(R[,1]),], nrow=2)
# Simulation based on BEKK Model
update_SIGMA <- function(SIGMA, Xi){
  update_SIGMA <- C %*% t(C) + A %*% (Xi %*% t(Xi)) %*% t(A) + B %*% SIGMA %*% t(B)
}
BEKK_Simu <- function(rept){
  Return_base <- matrix(rep((mu), T+1), nrow=2, byrow=F) # Constant mean vector
  SIGMA <- matrix(rep(Last.SIGMA,T+1), nrow=2, byrow=F) # For storing the conditional Variance Covariance Matrices
  Residual <- matrix(rep(Last.Residual,T+1), nrow=2, byrow=F) # For storing the residuals
  for (i in 2:(T+1)){
    SIGMA[,(2*i-1):(2*i)] <- update_SIGMA(SIGMA[,(2*i-3):(2*i-2)], Residual[,i-1])
    Residual[,i] <- mvrnorm(n = 1, mu = c(0,0), Sigma = SIGMA[,(2*i-1):(2*i)])
  }
  Sim_R <- Return_base + Residual
  Sim_R[,1] <- c(0,0)
  Sim_S <- exp(t(apply(Sim_R, 1, cumsum))) * c(AAPL[length(AAPL)], AMZN[length(AMZN)])
  return(Sim_S)
}
Output_BEKK_AAPL <- matrix(0, nrow = P, ncol=T_3m+1)
Output_BEKK_AMZN <- Output_BEKK_AAPL
for (rept in 1:P){
  temp <- BEKK_Simu(rept)
  Output_BEKK_AAPL[rept,] <- temp[1,]
  Output_BEKK_AMZN[rept,] <- temp[2,]
}

save(Output_BEKK_AAPL, Output_BEKK_AMZN, file='bekkData.rda')
```


```{r data for analysis}
# use offline simulation data
# rm(S1_gen, S2_gen, Output_BEKK_AAPL, Output_BEKK_AMZN)
# load(file = "bekkData.rda")
# load(file = "gbmData.rda")

simulationResults <- data.frame(alpha=double(),
                        beta=double(),
                        K=double(),
                        VaR99_1m_GBM_PTFL=double(), 
                        VaR99_1m_GARCH_PTFL=double(), 
                        ES99_1m_GBM_PTFL=double(), 
                        ES99_1m_GARCH_PTFL=double(),
                        mean_1m_GBM_PTFL=double(),
                        mean_1m_GARCH_PTFL=double(),
                        median_1m_GBM_PTFL=double(),
                        median_1m_GARCH_PTFL=double(),
                        VaR99_3m_GBM_PTFL=double(), 
                        VaR99_3m_GARCH_PTFL=double(), 
                        ES99_3m_GBM_PTFL=double(), 
                        ES99_3m_GARCH_PTFL=double(),
                        mean_3m_GBM_PTFL=double(),
                        mean_3m_GARCH_PTFL=double(),
                        median_3m_GBM_PTFL=double(),
                        median_3m_GARCH_PTFL=double()
                        )
sum_V_0 = sum(V_0)
for (a in seq(from=0.5, to=1.5, by=0.5)) {
  for (b in seq(from=0.5, to=1.5, by=0.5)) {
    for (k in seq(from=1, to=5, by=2)) {
      # rs stands for result set
      rsBS_ptfl <- GSLS_Ptfl(price1 = S1_gen, price2 = S2_gen,I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
      
      rsBEKK_ptfl <- GSLS_Ptfl(price1 = Output_BEKK_AAPL, price2 = Output_BEKK_AMZN,I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)

      # initialize portfolio calculation
      gbmPftlRet3m   = rsBS_ptfl$return3m
      gbmPftlRet1m   = rsBS_ptfl$return1m
      garchPftlRet3m = rsBEKK_ptfl$return3m 
      garchPftlRet1m = rsBEKK_ptfl$return1m

      # plot histogram and denity curve
      hist( gbmPftlRet1m,   main=paste("Histogram of Portfolio Return under BS Model \n with alpha=", a, " beta=", b, " K=", k, "T=1 Month"), xlim =c(min(gbmPftlRet1m)-0.1, max(gbmPftlRet1m)+0.1),breaks = 20, xlab="Return")
      dens=density(gbmPftlRet1m)
      lines(dens$x,length(gbmPftlRet1m) * (max(gbmPftlRet1m) - min(gbmPftlRet1m)) *dens$y / 20) 
      abline(v=mean(gbmPftlRet1m),col=3) # green line for mean
      abline(v=-getVaR(gbmPftlRet1m, pct99),col=2) # red line for 99% VaR
      
      hist( garchPftlRet1m, main=paste("Histogram of Portfolio Return under GARCH Model \n with alpha =", a, " beta=", b, " K=", k, "T=1 Month"), xlim =c(min(garchPftlRet1m)-0.1, max(garchPftlRet1m)+0.1),breaks = 20, xlab="Return")
      dens=density(garchPftlRet1m)
      lines(dens$x,length(garchPftlRet1m) * (max(garchPftlRet1m) - min(garchPftlRet1m)) *dens$y / 20) 
      abline(v=mean(garchPftlRet1m),col=3) # green line for mean
      abline(v=-getVaR(garchPftlRet1m, pct99),col=2) # red line for 99% VaR
      
      hist( gbmPftlRet3m,   main=paste("Histogram of Portfolio Return under BS Model \n with alpha=", a, " beta=", b, " K=", k, "T=3 Months"), xlim =c(min(gbmPftlRet3m)-0.1, max(gbmPftlRet3m)+0.1),breaks = 20, xlab="Return")
      dens=density(gbmPftlRet3m)
      lines(dens$x,length(gbmPftlRet3m) * (max(gbmPftlRet3m) - min(gbmPftlRet3m)) *dens$y / 20) 
      abline(v=mean(gbmPftlRet3m),col=3) # green line for mean
      abline(v=-getVaR(gbmPftlRet3m, pct99),col=2) # red line for 99% VaR
      
      hist( garchPftlRet3m, main=paste("Histogram of Portfolio Return under GARCH Model with \n alpha =", a, " beta =", b, " K=", k, "T = 3 Months"), xlim =c(min(garchPftlRet3m)-0.1, max(garchPftlRet3m)+0.1),breaks = 20, xlab="Return")
      dens=density(garchPftlRet3m)
      lines(dens$x,length(garchPftlRet3m) * (max(garchPftlRet3m) - min(garchPftlRet3m)) *dens$y / 20)
      abline(v=mean(garchPftlRet3m),col=3) # green line for mean
      abline(v=-getVaR(garchPftlRet3m, pct99),col=2) # red line for 99% VaR
            
      # plot contour
      sample = apply( (rsBS_ptfl$allV - sum_V_0) / sum_V_0, 2, quantile, probs=c(0.01, 0.5, 0.99))
      plot.zoo(t( (rsBS_ptfl$allV - sum_V_0) / sum_V_0 ), main = paste("Sample Return Paths and Empirical Confidence Envelope\n(BS Model) ", "alpha=", a, " beta=", b, " K=", k), xlab="t", ylab="Portfolio Return", plot.type = "single")
      lines(sample[1,],col="Red",lwd=2)
      lines(sample[2,],col="Red",lwd=2)
      lines(sample[3,],col="Red",lwd=2)
      #plot(c(1:253, 1:253, 1:253), c(sample[1,],sample[2,],sample[3,]), type="l", main=paste("Contour of Portfolio Simulation based on GBM Model", "alpha =", a, " beta =", b, " K=", k), xlab="time", ylab="pct return")
      abline(h=0,col=3) # green line for 0

      
      sample = apply( (rsBEKK_ptfl$allV - sum_V_0) / sum_V_0, 2, quantile, probs=c(0.01, 0.5, 0.99))
      plot.zoo(t((rsBEKK_ptfl$allV - sum_V_0) / sum_V_0), main = paste("Sample Return Paths and Empirical Confidence Envelope\n(BEKK Model) ", "alpha=", a, " beta=", b, " K=", k), xlab="t", ylab="Portfolio Return", plot.type = "single")
      lines(sample[1,],col="Red",lwd=2)
      lines(sample[2,],col="Red",lwd=2)
      lines(sample[3,],col="Red",lwd=2)
      #plot(c(1:253, 1:253, 1:253), c(sample[1,],sample[2,],sample[3,]), type="l", main=paste("ontour of Portfolio Simulation based on BEKK Model", "alpha =", a, " beta =", b, " K=", k), xlab="time", ylab="pct return")
      abline(h=0,col=3) # green line for 0

      
      #save stimulation result
      stimulationRec <- data.frame(alpha=a,
                        beta=b,
                        K=k,
                        ### 3 mths
                        VaR99_3m_GBM_PTFL  =getVaR(gbmPftlRet3m, pct99), 
                        VaR99_3m_GARCH_PTFL=getVaR(garchPftlRet3m, pct99), 
                        ES99_3m_GBM_PTFL   =getES(gbmPftlRet3m, pct99), 
                        ES99_3m_GARCH_PTFL =getES(garchPftlRet3m, pct99),
                        mean_3m_GBM_PTFL=mean(gbmPftlRet3m),
                        mean_3m_GARCH_PTFL=mean(garchPftlRet3m),
                        median_3m_GBM_PTFL=median(gbmPftlRet3m),
                        median_3m_GARCH_PTFL=median(garchPftlRet3m),
                        
                        ### 1 month
                        VaR99_1m_GBM_PTFL  =getVaR(gbmPftlRet1m, pct99), 
                        VaR99_1m_GARCH_PTFL=getVaR(garchPftlRet1m, pct99), 
                        ES99_1m_GBM_PTFL   =getES(gbmPftlRet1m, pct99), 
                        ES99_1m_GARCH_PTFL =getES(garchPftlRet1m, pct99),
                        mean_1m_GBM_PTFL=mean(gbmPftlRet1m),
                        mean_1m_GARCH_PTFL=mean(garchPftlRet1m),
                        median_1m_GBM_PTFL=median(gbmPftlRet1m),
                        median_1m_GARCH_PTFL=median(garchPftlRet1m)
                        )
      simulationResults <- rbind(simulationResults, stimulationRec)
    }
  }
}
# setwd("C:/Documents and Settings/Data")
save(simulationResults, file = "simulationResults.rda")
write.csv(simulationResults,'simulationResults.csv')
```

```{r historic data of 2007}
price_AAPL <- as.numeric(getSymbols("AAPL", from ="2007-01-01", to = "2008-01-03", auto.assign = FALSE)$AAPL.Close)
price_AMZN <- as.numeric(getSymbols("AMZN", from ="2007-01-01", to = "2008-01-03", auto.assign = FALSE)$AMZN.Close)
length(price_AAPL)
S_AAPL = matrix(price_AAPL, ncol=252)
S_AMZN = matrix(price_AMZN, ncol=252)
rs_hist1   <- GSLS(price = S_AAPL, I0 = I_0[1], V0 = V_0[1], alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_hist2   <- GSLS(price = S_AMZN, I0 = I_0[2], V0 = V_0[2], alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_ptfl_hist   <- GSLS_Ptfl(price1 = S_AAPL, price2 = S_AMZN, I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_hist1$return1m
rs_hist2$return1m 
rs_ptfl_hist$return1m
```

```{r historic data of 2008 }
price_AAPL <- as.numeric(getSymbols("AAPL", from ="2008-09-01", to = "2008-12-31", auto.assign = FALSE)$AAPL.Close)
price_AMZN <- as.numeric(getSymbols("AMZN", from ="2008-09-01", to = "2008-12-31", auto.assign = FALSE)$AMZN.Close)
length(price_AAPL)
S_AAPL = matrix(price_AAPL, ncol=length(price_AAPL))
S_AMZN = matrix(price_AMZN, ncol=length(price_AMZN))
rs_hist1   <- GSLS(price = S_AAPL, I0 = I_0[1], V0 = V_0[1], alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_hist2   <- GSLS(price = S_AMZN, I0 = I_0[2], V0 = V_0[2], alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_ptfl_hist   <- GSLS_Ptfl(price1 = S_AAPL, price2 = S_AMZN, I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
rs_hist1$return1m
rs_hist2$return1m 
rs_ptfl_hist$return1m
```

Backfeeding data to the SLS for data analysis
# Pre-requisite: Please run Global Variables and Helper Functions first!
```{r Back-feed historical data analysis - download data for optimization}

################################## 4 scenario ###################################
# Beware that getSymbols(..to=20180101) exclude 20180101!  type 1 day after!    # 
# Set 1:                                                                        #
# 1.Drop: 20071008-20080108 (-43.22%);     3m data for optim: 20070710-20071008 #
# 2.Rise: 20090305-20090604 (+250.00%);    3m data for optim: 20081202-20090305 #
# 3.Stable:20070321-20070620 (sd 15.70%);  3m data for optim: 20061215-20070321 #
# 4.Volatile:20080903-20081202 (sd207.13%);3m data for optim: 20080604-20080903 #
#################################################################################
# Set 2:                                                                        #
# 1.Drop: 20071206-20080310 (-42.68%);     3m data for optim: 20070907-20071206 #
# 2.Rise: 20090727-20091023 (+65.80%);     3m data for optim: 20090427-20090727 #
# 3.Stable:20060824-20061122 (sd 9.29%);   3m data for optim: 20060525-20060824 #
# 4.Volatile:20090122-20090423 (sd203.46%);3m data for optim: 20081021-20090122 #
#################################################################################
# Set 3:                                                                        #
# 1.Drop: 20080822-20081120 (-74.04%);     3m data for optim: 20080523-20080822 #
# 2.Rise: 20120724-20121022 (+49.45%);     3m data for optim: 20120424-20120724 #
# 3.Stable:20060509-20060808 (sd 15.78%);  3m data for optim: 20060207-20060509 #
# 4.Volatile:20090227-20090529 (sd197.85%);3m data for optim: 20081125-20090227 #
#################################################################################

# download Citigroup price
library(quantmod)
# For Drop
  price_C_dropForOpt1 <- as.numeric(getSymbols("C", from ="2007-07-10", to = "2007-10-09", auto.assign = FALSE)$C.Close)
  price_C_dropForOpt2 <- as.numeric(getSymbols("C", from ="2007-09-07", to = "2007-12-07", auto.assign = FALSE)$C.Close)
  price_C_dropForOpt3 <- as.numeric(getSymbols("C", from ="2008-05-23", to = "2008-08-23", auto.assign = FALSE)$C.Close)
  
  length(price_C_dropForOpt1)
  length(price_C_dropForOpt2)
  length(price_C_dropForOpt3)
  
  if( length(price_C_dropForOpt1)!=length(price_C_dropForOpt2) |
      length(price_C_dropForOpt2)!=length(price_C_dropForOpt3) | 
      length(price_C_dropForOpt1)!=length(price_C_dropForOpt3)) {
      message("Drop Case: length of downloaded prices are inconsistent")
  }else{
      S_C_dropForOpt = matrix(c(price_C_dropForOpt1,price_C_dropForOpt2,price_C_dropForOpt3), byrow=TRUE, nrow=3)  
  }


# For Rise
  price_C_riseForOpt1 <- as.numeric(getSymbols("C", from ="2008-12-02", to = "2009-03-06", auto.assign = FALSE)$C.Close)
  price_C_riseForOpt2 <- as.numeric(getSymbols("C", from ="2009-04-27", to = "2009-07-28", auto.assign = FALSE)$C.Close)
  price_C_riseForOpt3 <- as.numeric(getSymbols("C", from ="2012-04-24", to = "2012-07-25", auto.assign = FALSE)$C.Close)
  
  length(price_C_riseForOpt1)
  length(price_C_riseForOpt2)
  length(price_C_riseForOpt3)
  
  if( length(price_C_riseForOpt1)!=length(price_C_riseForOpt2) |
      length(price_C_riseForOpt2)!=length(price_C_riseForOpt3) | 
      length(price_C_riseForOpt1)!=length(price_C_riseForOpt3)) {
      message("Rise Case: length of downloaded prices are inconsistent")
  }else{
      S_C_riseForOpt = matrix(c(price_C_riseForOpt1,price_C_riseForOpt2,price_C_riseForOpt3), byrow=TRUE,nrow=3)  
  }


# For Stable
  price_C_stabForOpt1 <- as.numeric(getSymbols("C", from ="2006-12-15", to = "2007-03-22", auto.assign = FALSE)$C.Close)
  price_C_stabForOpt2 <- as.numeric(getSymbols("C", from ="2006-05-25", to = "2006-08-25", auto.assign = FALSE)$C.Close)
  price_C_stabForOpt3 <- as.numeric(getSymbols("C", from ="2006-02-07", to = "2006-05-10", auto.assign = FALSE)$C.Close)
  
  length(price_C_stabForOpt1)
  length(price_C_stabForOpt2)
  length(price_C_stabForOpt3)
  
  if( length(price_C_stabForOpt1)!=length(price_C_stabForOpt2) |
      length(price_C_stabForOpt2)!=length(price_C_stabForOpt3) | 
      length(price_C_stabForOpt1)!=length(price_C_stabForOpt3)) {
      message("Stable Case: length of downloaded prices are inconsistent")
  }else{
      S_C_stabForOpt = matrix(c(price_C_stabForOpt1,price_C_stabForOpt2,price_C_stabForOpt3), byrow=TRUE,nrow=3)  
  }
  

# For Volatile
  price_C_volForOpt1 <- as.numeric(getSymbols("C", from ="2008-06-04", to = "2008-09-04", auto.assign = FALSE)$C.Close)
  price_C_volForOpt2 <- as.numeric(getSymbols("C", from ="2008-10-21", to = "2009-01-23", auto.assign = FALSE)$C.Close)
  price_C_volForOpt3 <- as.numeric(getSymbols("C", from ="2008-11-25", to = "2009-02-28", auto.assign = FALSE)$C.Close)
  
  length(price_C_volForOpt1)
  length(price_C_volForOpt2)
  length(price_C_volForOpt3)
  
  if( length(price_C_volForOpt1)!=length(price_C_volForOpt2) |
      length(price_C_volForOpt2)!=length(price_C_volForOpt3) | 
      length(price_C_volForOpt1)!=length(price_C_volForOpt3)) {
      message("Volatile Case: length of downloaded prices are inconsistent")
  }else{
      S_C_volForOpt = matrix(c(price_C_volForOpt1,price_C_volForOpt2,price_C_volForOpt3), byrow=TRUE,nrow=3)  
  }

```



```{r Back-feed historical data analysis - optimization}
simulationResults <- data.frame(setNum=double(),
                        alpha=double(),
                        beta=double(),
                        K=double(),
                        bfPftlRet3m_drop=double(),
                        bfPftlRet3m_rise=double(),
                        bfPftlRet3m_stab=double(),
                        bfPftlRet3m_vol=double()
                        )

sum_V_0 = sum(V_0)

    ret_drop_max = rep(-1,3)
    ret_rise_max = rep(-1,3)
    ret_stab_max = rep(-1,3)
    ret_vol_max  = rep(-1,3)
    a_drop_max   = rep(0,3)
    b_drop_max   = rep(0,3)
    k_drop_max   = rep(0,3)
    a_rise_max   = rep(0,3)
    b_rise_max   = rep(0,3)
    k_rise_max   = rep(0,3)
    a_stab_max   = rep(0,3)
    b_stab_max   = rep(0,3)
    k_stab_max   = rep(0,3)
    a_vol_max    = rep(0,3)
    b_vol_max    = rep(0,3)
    k_vol_max    = rep(0,3)
    
for (i in seq(1,3,1)){
        
    for (a in seq(from=0.5, to=1.5, by=0.5)) {
      for (b in seq(from=0.5, to=1.5, by=0.5)) {
        for (k in seq(from=1, to=5, by=2)) {
    
          rsBF_ptfl_drop <- GSLS_Ptfl(price1 = matrix(S_C_dropForOpt[i,],nrow=1), price2 = matrix(S_C_dropForOpt[i,],nrow=1), I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
          rsBF_ptfl_rise <- GSLS_Ptfl(price1 = matrix(S_C_riseForOpt[i,],nrow=1), price2 = matrix(S_C_riseForOpt[i,],nrow=1), I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
          rsBF_ptfl_stab <- GSLS_Ptfl(price1 = matrix(S_C_stabForOpt[i,],nrow=1), price2 = matrix(S_C_stabForOpt[i,],nrow=1), I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
          rsBF_ptfl_vol <- GSLS_Ptfl(price1 = matrix(S_C_volForOpt[i,],nrow=1), price2 = matrix(S_C_volForOpt[i,],nrow=1), I0 = I_0, V0 = sum(V_0), alpha = a, beta = b, gamma = g, K = k, r=dailyRiskFeeRate, Imin = I_min)
          
          # initialize portfolio calculation
          bfPftlRet3m_drop   = rsBF_ptfl_drop$return3m
          bfPftlRet3m_rise   = rsBF_ptfl_rise$return3m
          bfPftlRet3m_stab   = rsBF_ptfl_stab$return3m
          bfPftlRet3m_vol    = rsBF_ptfl_vol$return3m      
          
          #record optimized parameters
          if(bfPftlRet3m_drop > ret_drop_max[i]) {
            ret_drop_max[i] = bfPftlRet3m_drop
            a_drop_max[i] = a
            b_drop_max[i] = b
            k_drop_max[i] = k
          } 
          if(bfPftlRet3m_rise > ret_rise_max[i]) {
            ret_rise_max[i] = bfPftlRet3m_rise
            a_rise_max[i] = a
            b_rise_max[i] = b
            k_rise_max[i] = k
          } 
          if(bfPftlRet3m_stab > ret_stab_max[i]) {
            ret_stab_max[i] = bfPftlRet3m_stab
            a_stab_max[i] = a
            b_stab_max[i] = b
            k_stab_max[i] = k
          } 
          if(bfPftlRet3m_vol > ret_vol_max[i]) {
            ret_vol_max[i] = bfPftlRet3m_vol
            a_vol_max[i] = a
            b_vol_max[i] = b
            k_vol_max[i] = k
          } 
          #save stimulation result
          simulationRec <- data.frame(setNum=i,
                            alpha=a,
                            beta=b,
                            K=k,
                            bfPftlRet3m_drop,
                            bfPftlRet3m_rise,
                            bfPftlRet3m_stab,
                            bfPftlRet3m_vol
                            )
          simulationResults <- rbind(simulationResults, simulationRec)
        }
      }
    }
    message("Set ",i,"\n",
      "Drop case max return =     ", round(ret_drop_max[i],4), " with a = ", a_drop_max[i], ", b = ", b_drop_max[i], ", k = ", k_drop_max[i], "\n",
    "Rise case max return =     ", round(ret_rise_max[i],4), " with a = ", a_rise_max[i], ", b = ", b_rise_max[i], ", k = ", k_rise_max[i], "\n",
    "Stable case max return =   ", round(ret_stab_max[i],4), " with a = ", a_stab_max[i], ", b = ", b_stab_max[i], ", k = ", k_stab_max[i], "\n",
    "Volatile case max return = ", round(ret_vol_max[i],4), " with a = ", a_vol_max[i], ", b = ", b_vol_max[i], ", k = ", k_vol_max[i],"\n")
}
write.csv(simulationResults,'optimizationResults(backfeed).csv')
```



```{r Back-feed historical data analysis - backfeed to strategy}

################################## 4 scenario ###################################
# Beware that getSymbols(..to=20180101) exclude 20180101!  type 1 day after!    # 
# Set 1:                                                                        #
# 1.Drop: 20071008-20080108 (-43.22%);     3m data for optim: 20070710-20071008 #
# 2.Rise: 20090305-20090604 (+250.00%);    3m data for optim: 20081202-20090305 #
# 3.Stable:20070321-20070620 (sd 15.70%);  3m data for optim: 20061215-20070321 #
# 4.Volatile:20080903-20081202 (sd207.13%);3m data for optim: 20080604-20080903 #
#################################################################################
# Set 2:                                                                        #
# 1.Drop: 20071206-20080310 (-42.68%);     3m data for optim: 20070907-20071206 #
# 2.Rise: 20090727-20091023 (+65.80%);     3m data for optim: 20090427-20090727 #
# 3.Stable:20060824-20061122 (sd 9.29%);   3m data for optim: 20060525-20060824 #
# 4.Volatile:20090122-20090423 (sd203.46%);3m data for optim: 20081021-20090122 #
#################################################################################
# Set 3:                                                                        #
# 1.Drop: 20080822-20081120 (-74.04%);     3m data for optim: 20080523-20080822 #
# 2.Rise: 20120724-20121022 (+49.45%);     3m data for optim: 20120424-20120724 #
# 3.Stable:20060509-20060808 (sd 15.78%);  3m data for optim: 20060207-20060509 #
# 4.Volatile:20090227-20090529 (sd197.85%);3m data for optim: 20081125-20090227 #
#################################################################################


# download Citigroup price
library(quantmod)

    # For Drop
    price_C_drop1 <- as.numeric(getSymbols("C", from ="2007-10-08", to = "2008-01-09", auto.assign = FALSE)$C.Close)
    price_C_drop2 <- as.numeric(getSymbols("C", from ="2007-12-06", to = "2008-03-11", auto.assign = FALSE)$C.Close)    
    price_C_drop3 <- as.numeric(getSymbols("C", from ="2008-08-22", to = "2008-11-21", auto.assign = FALSE)$C.Close)
    
    length(price_C_drop1)
    length(price_C_drop2)
    length(price_C_drop3)
    if( length(price_C_drop1)!=length(price_C_drop2) |
        length(price_C_drop2)!=length(price_C_drop3) | 
        length(price_C_drop1)!=length(price_C_drop3)) {
        message("Drop Case: length of downloaded prices are inconsistent")
    }else{
      S_C_drop = matrix(c(price_C_drop1,price_C_drop2,price_C_drop3), byrow=TRUE, nrow=3)  
    }
    
    
    # For Rise
    price_C_rise1 <- as.numeric(getSymbols("C", from ="2009-03-05", to = "2009-06-05", auto.assign = FALSE)$C.Close)
    price_C_rise2 <- as.numeric(getSymbols("C", from ="2009-07-27", to = "2009-10-24", auto.assign = FALSE)$C.Close)
    price_C_rise3 <- as.numeric(getSymbols("C", from ="2009-07-24", to = "2009-10-23", auto.assign = FALSE)$C.Close)
    
    length(price_C_rise1)
    length(price_C_rise2)
    length(price_C_rise3)
    if( length(price_C_rise1)!=length(price_C_rise2) |
        length(price_C_rise2)!=length(price_C_rise3) | 
        length(price_C_rise1)!=length(price_C_rise3)) {
        message("Rise Case: length of downloaded prices are inconsistent")
    }else{
      S_C_rise = matrix(c(price_C_rise1,price_C_rise2,price_C_rise3), byrow=TRUE, nrow=3)  
    }
    
    

    # For Stable
    price_C_stab1 <- as.numeric(getSymbols("C", from ="2007-03-21", to = "2007-06-21", auto.assign = FALSE)$C.Close)
    price_C_stab2 <- as.numeric(getSymbols("C", from ="2006-08-24", to = "2006-11-23", auto.assign = FALSE)$C.Close)
    price_C_stab3 <- as.numeric(getSymbols("C", from ="2006-05-09", to = "2006-08-09", auto.assign = FALSE)$C.Close)
    
    length(price_C_stab1)
    length(price_C_stab2)
    length(price_C_stab3)
    if( length(price_C_stab1)!=length(price_C_stab2) |
        length(price_C_stab2)!=length(price_C_stab3) | 
        length(price_C_stab1)!=length(price_C_stab3)) {
        message("Stable Case: length of downloaded prices are inconsistent")
    }else{
      S_C_stab = matrix(c(price_C_stab1,price_C_stab2,price_C_stab3), byrow=TRUE, nrow=3)  
    }
    
    
    # For Volatile
    price_C_vol1 <- as.numeric(getSymbols("C", from ="2008-09-03", to = "2008-12-03", auto.assign = FALSE)$C.Close)
    price_C_vol2 <- as.numeric(getSymbols("C", from ="2009-01-22", to = "2009-04-24", auto.assign = FALSE)$C.Close)
    price_C_vol3 <- as.numeric(getSymbols("C", from ="2009-02-27", to = "2009-05-30", auto.assign = FALSE)$C.Close)
    
    length(price_C_vol1)
    length(price_C_vol2)
    length(price_C_vol3)
    if( length(price_C_vol1)!=length(price_C_vol2) |
        length(price_C_vol2)!=length(price_C_vol3) | 
        length(price_C_vol1)!=length(price_C_vol3)) {
        message("Volatile Case: length of downloaded prices are inconsistent")
    }else{
      S_C_vol = matrix(c(price_C_vol1,price_C_vol2,price_C_vol3), byrow=TRUE, nrow=3)  
    }
    
############## use simple SLS with a=1, b=1, K=1 #############
    a_drop_max   = rep(1,3)
    b_drop_max   = rep(1,3)
    k_drop_max   = rep(1,3)
    a_rise_max   = rep(1,3)
    b_rise_max   = rep(1,3)
    k_rise_max   = rep(1,3)
    a_stab_max   = rep(1,3)
    b_stab_max   = rep(1,3)
    k_stab_max   = rep(1,3)
    a_vol_max    = rep(1,3)
    b_vol_max    = rep(1,3)
    k_vol_max    = rep(1,3)
#################################################################        
    
for (i in 1:3){    
  # Fit data to GSLS function
      rs_hist_drop = GSLS_Ptfl(price1 = matrix(S_C_drop[i,],nrow=1), price2 = matrix(S_C_drop[i,],nrow=1), I0 = I_0[1], V0 = V_0[1], alpha = a_drop_max[i], beta = b_drop_max[i], gamma = g, K = k_drop_max[i], r=dailyRiskFeeRate, Imin = I_min)
      rs_hist_rise = GSLS_Ptfl(price1 = matrix(S_C_rise[i,],nrow=1), price2 = matrix(S_C_rise[i,],nrow=1), I0 = I_0[1], V0 = V_0[1], alpha = a_rise_max[i], beta = b_rise_max[i], gamma = g, K = k_rise_max[i], r=dailyRiskFeeRate, Imin = I_min)
      rs_hist_stab = GSLS_Ptfl(price1 = matrix(S_C_stab[i,],nrow=1), price2 = matrix(S_C_stab[i,],nrow=1), I0 = I_0[1], V0 = V_0[1], alpha = a_stab_max[i], beta = b_stab_max[i], gamma = g, K = k_stab_max[i], r=dailyRiskFeeRate, Imin = I_min)
      rs_hist_vol  = GSLS_Ptfl(price1 = matrix(S_C_vol[i,],nrow=1), price2 = matrix(S_C_vol[i,],nrow=1), I0 = I_0[1], V0 = V_0[1], alpha = a_vol_max[i], beta = b_vol_max[i], gamma = g, K = k_vol_max[i], r=dailyRiskFeeRate, Imin = I_min)
      
      
  
  # Plot graph
      # For Drop
      par(las=1)
      par(mar = c(5, 5, 3, 8))
      plot(S_C_drop[i,], type="l", ylim=c(min(S_C_drop[i,]),max(S_C_drop[i,])), main = paste("Set ", i," SLS Return in Bearish Market\n with alpha = ",a_drop_max[i], " beta = ", b_drop_max[i], " K = ", k_drop_max[i]), xlab="time", ylab="Stock Price", col="blue",lty=2)
      par(new=TRUE)
      plot(rs_hist_drop$allV[1,],type="l", axes=FALSE, xlab="", ylab="", col="orange", lwd=2.5)
      axis(side=4)
      mtext("Account Value", side = 4, line = 5, las=3)
      legend("bottom", c("SLS Return","Historical Stock Price"), col=c("orange","blue"), lty=c(1,2), cex=0.65)
      
      # For Rise
      par(las=1)
      par(mar = c(5, 5, 3, 8))
      plot(S_C_rise[i,], type="l", ylim=c(min(S_C_rise[i,]),max(S_C_rise[i,])), main = paste("Set ", i," SLS Return in Bullish Market\n with alpha = ",a_rise_max[i], " beta = ", b_rise_max[i], " K = ", k_rise_max[i]), xlab="time", ylab="Stock Price", col="blue",lty=2)
      par(new=TRUE)
      plot(rs_hist_rise$allV[1,],type="l", axes=FALSE, xlab="", ylab="", col="orange", lwd=2.5)
      axis(side=4)
      mtext("Account Value", side = 4, line = 5, las=3)
      legend("bottomright", c("SLS Return","Historical Stock Price"), col=c("orange","blue"), lty=c(1,2), cex=0.65)
      
      # For Stable
      par(las=1)
      par(mar = c(5, 5, 3, 8))
      plot(S_C_stab[i,], type="l", ylim=c(min(S_C_stab[i,]),max(S_C_stab[i,])), main = paste("Set ", i," SLS Return in Stable Market\n with alpha = ",a_stab_max[i], " beta = ", b_stab_max[i], " K = ", k_stab_max[i]), xlab="time", ylab="Stock Price", col="blue",lty=2)
      par(new=TRUE)
      plot(rs_hist_stab$allV[1,],type="l", axes=FALSE, xlab="", ylab="", col="orange", lwd=2.5)
      axis(side=4)
      mtext("Account Value", side = 4, line = 5, las=3)
      legend("top", c("SLS Return","Historical Stock Price"), col=c("orange","blue"), lty=c(1,2), cex=0.65)
      
      # For Volatile
      par(las=1)
      par(mar = c(5, 5, 3, 8))
      plot(S_C_vol[i,], type="l", ylim=c(min(S_C_vol[i,]),max(S_C_vol[i,])), main = paste("Set ", i," SLS Return in Volatile Market\n with alpha = ",a_vol_max[i], " beta = ", b_vol_max[i], " K = ", k_vol_max[i]), xlab="time", ylab="Stock Price", col="blue",lty=2)
      par(new=TRUE)
      plot(rs_hist_vol$allV[1,],type="l", axes=FALSE, xlab="", ylab="", col="orange", lwd=2.5)
      axis(side=4)
      mtext("Account Value", side = 4, line = 5, las=3)
      legend("bottom", c("SLS Return","Historical Stock Price"), col=c("orange","blue"), lty=c(1,2), cex=0.65)
  
      
    
# Calculate daily return of the feedback data, and Sharpe Ratio
    rs_hist_ret_drop = (rs_hist_drop$allV[1,2:ncol(rs_hist_drop$allV)] / rs_hist_drop$allV[1, 1:(ncol(rs_hist_drop$allV)-1)] -1)
    rs_hist_ret_rise = (rs_hist_rise$allV[1,2:ncol(rs_hist_rise$allV)] / rs_hist_rise$allV[1, 1:(ncol(rs_hist_rise$allV)-1)] -1)
    rs_hist_ret_stab = (rs_hist_stab$allV[1,2:ncol(rs_hist_stab$allV)] / rs_hist_stab$allV[1, 1:(ncol(rs_hist_stab$allV)-1)] -1)
    rs_hist_ret_vol = (rs_hist_vol$allV[1,2:ncol(rs_hist_vol$allV)] / rs_hist_vol$allV[1, 1:(ncol(rs_hist_vol$allV)-1)] -1)
    
    # 3-month return
    message("3-month return (Set ", i," drop) = ", rs_hist_drop$allV[1,ncol(rs_hist_drop$allV)] / rs_hist_drop$allV[1, 1] -1)
    message("3-month return (Set ", i," rise) = ", rs_hist_rise$allV[1,ncol(rs_hist_rise$allV)] / rs_hist_rise$allV[1, 1] -1)
    message("3-month return (Set ", i," stab) = ", rs_hist_stab$allV[1,ncol(rs_hist_stab$allV)] / rs_hist_stab$allV[1, 1] -1)
    message("3-month return (Set ", i," vol) = ", rs_hist_vol$allV[1,ncol(rs_hist_vol$allV)] / rs_hist_vol$allV[1, 1] -1)
    
    
    # Sharpe Ratio = [ mean(daily portfolio return) - R_f ] / daily portfolio SD
    message("Sharpe Ratio (Set ", i," drop) = ",  (252*mean(rs_hist_ret_drop)-360*dailyRiskFeeRate)/(sqrt(252)*sd(rs_hist_ret_drop)))
    message("Sharpe Ratio (Set ", i," rise) = ",  (252*mean(rs_hist_ret_rise)-360*dailyRiskFeeRate)/(sqrt(252)*sd(rs_hist_ret_rise)))
    message("Sharpe Ratio (Set ", i," stab) = ",  (252*mean(rs_hist_ret_stab)-360*dailyRiskFeeRate)/(sqrt(252)*sd(rs_hist_ret_stab)))
    message("Sharpe Ratio (Set ", i," vol) =  ",  (252*mean(rs_hist_ret_vol) -360*dailyRiskFeeRate)/(sqrt(252)*sd(rs_hist_ret_vol)))
}    
```