---
title: "Test"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unit Test Case 
pre-requisite: initialize the helper functions in SLS.Rmd 
```{r test case 01}
#test case 01
price   <- matrix(c(10,11,10,12,9,10,12,14,18,16,10), nrow=1)

GSLS(price, I0=100, V0=100, alpha=1.1, beta=0.9, gamma=1.5, K=2, r=0.0003, Imin=40)

price   <- matrix(c(10,11,10,12,9,10,12,14,18,16,10,11,10,12,9,10,12,14,18,16,10,11,10,12,9,10,12,14,18,16), nrow=1)

GSLS(price, I0=100, V0=100, alpha=1.1, beta=0.9, gamma=1.5, K=2, r=0.0003, Imin=40)
```

```{r test case 02}
#test case 02
price   <- rbind( c(10,11,10,12,9,10,12,14,18,16,10), c(10,11,10,12,9,10,12,14,18,16,10) )

GSLS(price, I0=100, V0=100, alpha=1, beta=1, gamma=1.5, K=2, r=0.0003, Imin=40)
```

```{r test case for VaR and ES}
sam <- c(-50:50)
quantile(sam,probs=0.95,na.rm=TRUE)

VaR <- getVaR(sam,0.95)
ES <- getES(sam,0.95)

VaR
ES

```

Running GSLS
```{r running_gsls}
g_S1 <- GSLS(S1_gen, I0=100, V0=100, alpha=1, beta=1, gamma=1.5, K=2, r=0.0003, Imin=40)
g_S2 <- GSLS(S2_gen, I0=100, V0=100, alpha=1, beta=1, gamma=1.5, K=2, r=0.0003, Imin=40)

g_AAPL <- GSLS(Output_AAPL, I0=100, V0=100, alpha=1, beta=1, gamma=1.5, K=2, r=0.0003, Imin=40)
g_AMZN <- GSLS(Output_AMZN, I0=100, V0=100, alpha=1, beta=1, gamma=1.5, K=2, r=0.0003, Imin=40)
```

Historam on gain
```{r gain}
hist(g_S1$gain10day)
hist(g_S2$gain10day)

hist(g_AAPL$gain10day)
hist(g_AMZN$gain10day)
```

```{r account value}
hist(g_S1$acctValue)
hist(g_S2$acctValue)

hist(g_AAPL$acctValue)
hist(g_AMZN$acctValue)
```

```{r VaR}
VaR_S1 <- getVaR(g_S1$gain10day,0.95)
VaR_S2 <- getVaR(g_S2$gain10day,0.95)

VaR_AAPL <- getVaR(g_AAPL$gain10day,0.95)
VaR_AMZN <- getVaR(g_AMZN$gain10day,0.95)

sprintf("VaR of AAPL=%f AMZN=%f", VaR_AAPL, VaR_AMZN)
sprintf("VaR of S1=%f S2=%f", VaR_S1, VaR_S2)
```

```{r ES on gain}
ES_S1 <- getES(g_S1$gain10day ,0.95)
ES_S2 <- getES(g_S2$gain10day,0.95)

ES_AAPL <- getES(g_AAPL$gain10day,0.95)
ES_AMZN <- getES(g_AMZN$gain10day ,0.95)

sprintf("Expected Shortfall of S1=%f S2=%f", ES_S1, ES_S2)
sprintf("Expected Shortfall of AAPL=%f AMZN=%f", ES_AAPL, ES_AMZN)
```

```{r VaR}
                        VaR_GBM_S1= getVaR(g_S1$gain1year, VaR95pct)
                        VaR_GBM_S2=getVaR(g_S2$gain1year, VaR95pct)
                        VaR_GBM_PTFL=getVaR(g_S1$gain1year+g_S2$gain1year, VaR95pct)
                        VaR_GARCH_S1=getVaR(g_AAPL$gain1year, VaR95pct)
                        VaR_GARCH_S2=getVaR(g_AMZN$gain1year, VaR95pct)
                        VaR_GARCH_PTFL=getVaR(g_BEKK_AAPL$gain1year+g_BEKK_AMZN$gain1year, VaR95pct) 
                        ES_GBM_S1=getES(g_S1$gain1year, VaR95pct)
                        ES_GBM_S2=getES(g_S2$gain1year, VaR95pct) 
                        ES_GBM_PTFL=getVaR(g_S1$gain1year+g_S2$gain1year, VaR95pct)
                        ES_GARCH_S1=getES(g_AAPL$gain1year, VaR95pct)
                        ES_GARCH_S2=getES(g_AMZN$gain1year, VaR95pct) 
                        ES_GARCH_PTFL=getVaR(g_BEKK_AAPL$gain1year+g_BEKK_AMZN$gain1year, VaR95pct)
```

